### ISSUE TITLE
Inventory components

### ISSUE THREAD

**Issue by fureigh** [18F/web-design-standards-drupal-d7#15]

**Comment by AlexBrown-appnovation** [comment]
I'm currently working on a backlog of  default components that will need customization in order to achieve parity with the US Web Design Standards playbook. I'm looking to release it over the next week or so - starting in this issue thread.

**Comment by AlexBrown-appnovation** [comment]
Current Inventory List:

**Comment by fureigh** [comment]
@AlexBrown-appnovation Great! Is your work in progress in a shareable format? Mine's in a sketchbook but I'll be typing it up soon.

**Comment by fureigh** [comment]
Odd... I got a GitHub notification for "Current Inventory List." Perhaps the comment's been deleted.

**Comment by AlexBrown-appnovation** [comment]
This is based on what is listed in https://playbook.cio.gov/designstandards/ page, as well as the output of the Styleguide module when the theme is activated and you navigate to /admin/appearance/styleguide/us_web_design_standards.

### Phase 1 - Playbook
- [x] Unordered List - **COMPLETE**
- [x] Ordered List - **COMPLETE**
- [ ] Buttons
- [ ] Tables
- [x] Alerts (Success, Warning, Error, Information) - **COMPLETE**
- Form Elements
  - [ ] text input
  - [ ] textarea
  - [ ] dropdown (select)
  - [ ] checkboxes
  - [ ] radio buttons
- [ ] Form Templates
- [ ] Sign-in Form
- [ ] Password Reset Form
- [ ] Search Bar - **IN PROGRESS**
- [x] Side Navigation (with title, 3 levels) - **COMPLETE**
- [ ] Footers (Big, Medium, Slim) 

### Phase 1 - Drupal Specific
- [ ] Body & Sidebar template logic - **IN PROGRESS**
- [x] Tabs - **COMPLETE**
- [x] Toolbar (Core Module) - **COMPLETE**
- [ ] Administration Menu (Contrib Module)
- [ ] Fieldsets (Collapsed, Collapsible)
- Forms
  - [ ] Vertical Tabs (node edit)
- [ ] Search, No Results
- [ ] Search Results
- [ ] Pager
- [ ] Breadcrumb (still to be designed by 18F)

### Phase 2 - Playbook
- Labels
- Accordions
- Form Elements
  - date input
- Form Templates
  - name form
  - address form

The ultimate goal here is to create tasks out of this list that the community can take on like a project backlog.

**Comment by fureigh** [comment]
I'll start creating tasks for these components, making a `d7`\- and `d8`-tagged issue for each for the sake of clarity. Thanks again for this rundown, @AlexBrown-appnovation.

If it becomes necessary to have more of a living document for this list, I can open this repo's wiki, but right now that seems like overkill.

**Comment by iris-i** [comment]
Thanks for building out these stub tickets @fureigh. Are we also looking to tame some extra drupal markup that comes with some of these elements? Wondering if some template overrides for things like the search form, menus, blocks etc. will be useful?
Referring to the drupal 7 theme, since drupal 8 already strips a lot of extra markup & classes
cc: @AlexBrown-appnovation

**Comment by AlexBrown-appnovation** [comment]
I would say that you're going for 1:1 parity (within reason) to the USWDS markup. So any template overrides etc that you need to incorporate to do so would be a good idea!

**Comment by patrickcate** [comment]
The various alerts are marked as completed, but they are appearing unstyled to me in the D7 version:

![screen shot 2016-04-24 at 9 55 35 pm](https://cloud.githubusercontent.com/assets/6277206/14772071/8b1f7dc4-0a67-11e6-8110-b0d7d5077e59.png)
